env:
  browser: true
  es2021: true
extends:
  - google
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  "require-jsdoc" : 0,
   "no-invalid-this": "off",
  'max-len': ["error", { "code": 120 }],
  }
