require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-i18n
  - rubocop-performance
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'config/**/*.rb'
    - 'app/admin/*.rb'
Layout/LineLength:
  Exclude:
    - 'config/initializers/*.rb'
Metrics/MethodLength:
  Exclude:
    - 'db/**/*.rb'
I18n/RailsI18n/DecorateString:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Max: 6
AllCops:
  SuggestExtensions: false
Metrics/AbcSize:
  Exclude:
    - 'db/**/*.rb'