version: 2.1

orbs:
  ruby: circleci/ruby@1.7.1
  node: circleci/node@5.0.2
  browser-tools: circleci/browser-tools@1.3.0
jobs:
  rspec:
    docker:
      - image: cimg/ruby:3.0.3-node
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: pizzeria
    environment:
      RAILS_ENV: test
      PGHOST: 127.0.0.1
      PGUSER: pizzeria
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
      - browser-tools/install-firefox
      - browser-tools/install-geckodriver
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          command: bundle exec rails db:create
      - run:
          command: bundle exec rails db:migrate
      - run:
          command: yarn add @popperjs/core
      - run:
          command: bundle exec rails assets:precompile
      - ruby/rspec-test
      - store_artifacts:
          path: coverage
  linters:
    docker:
      - image: cimg/ruby:3.0.3-node
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: bundle exec rubocop
      - run:
          command: bundle exec fasterer
  security:
    docker:
      - image: cimg/ruby:3.0.3-node
    steps:
      - checkout
      - ruby/install-deps
      - run:
          command: bundle exec brakeman
      - run:
          command: bundle exec bundle-audit
workflows:
  build:
    jobs:
      - rspec
      - linters
      - security
